import type { PlayerRanking, PlayerRankingRow } from "@/features/chat/types";

function sampleRow(
  overrides: Partial<PlayerRankingRow> & Pick<PlayerRankingRow, "rank" | "playerId" | "name" | "initials" | "value" | "sortValue" | "goals" | "assists" | "minutes" | "position">,
): PlayerRankingRow {
  return {
    teamCode: "ARG",
    clubTeam: "Test Club",
    appearances: 5,
    yellowCards: 0,
    redCards: 0,
    heightCm: 180,
    age: 27,
    starts: 5,
    penaltyGoals: 0,
    saves: null,
    cleanSheets: null,
    goalsConceded: null,
    ...overrides,
  };
}

export const sampleRanking: PlayerRanking = {
  id: "sample-ranking-goals",
  scope: "world_cup",
  rankBy: "goals",
  rankByLabel: "Goals",
  scopeLabel: "WC 2026 · Goals",
  footerCaption: "4 players · tournament stats",
  rows: [
    sampleRow({
      rank: 1,
      playerId: "1",
      name: "Kylian Mbappé",
      initials: "KM",
      teamCode: "FRA",
      clubTeam: "Real Madrid",
      position: "FWD",
      value: "8",
      sortValue: 8,
      goals: 8,
      assists: 3,
      minutes: 450,
      heightCm: 178,
      age: 27,
    }),
    sampleRow({
      rank: 2,
      playerId: "2",
      name: "Test Striker",
      initials: "TS",
      position: "FWD",
      value: "6",
      sortValue: 6,
      goals: 6,
      assists: 2,
      minutes: 450,
    }),
    sampleRow({
      rank: 3,
      playerId: "3",
      name: "Test Peer Forward",
      initials: "TP",
      position: "FWD",
      value: "1",
      sortValue: 1,
      goals: 1,
      assists: 0,
      minutes: 270,
      starts: 3,
    }),
    sampleRow({
      rank: 4,
      playerId: "4",
      name: "Test Keeper",
      initials: "TK",
      position: "GK",
      value: "0",
      sortValue: 0,
      goals: 0,
      assists: 0,
      minutes: 450,
      saves: 12,
      cleanSheets: 3,
      goalsConceded: 4,
    }),
  ],
};
