import type { ComparedTeam, TeamComparison, TeamRates } from "@/features/chat/team-comparison";
import {
  argentinaDef,
  argentinaFwd,
  argentinaGk,
  argentinaMid,
  brazilDef,
  brazilFwd,
  brazilGk,
  brazilMid,
  samplePositionGroup,
} from "@/features/chat/sample-data/team-comparison-squad";

/**
 * Illustrative placeholders, same rule as the other sample widgets.
 * Argentina numbers follow sampleTeam; Brazil is a contrasting side.
 */

const RATES: TeamRates = {
  goalsPerGame: 2,
  concededPerGame: 0.71,
  xgFor: 12.4,
  xgAgainst: 5.1,
  xgDifference: 7.3,
  xgPerGame: 1.77,
  xgAgainstPerGame: 0.73,
  possessionPct: 58.4,
  shotsPerGame: 15.3,
  shotsOnTargetPerGame: 6.1,
  shotAccuracyPct: 39.9,
  conversionPct: 32.8,
  cornersPerGame: 6.4,
  foulsPerGame: 10.9,
  offsidesPerGame: 1.7,
  saves: 18,
  savesPerGame: 2.57,
  cleanSheets: 3,
  cleanSheetsPerGame: 0.43,
};

function side(
  partial: Pick<ComparedTeam, "id" | "code" | "name" | "standingLabel" | "record" | "goalDifference" | "rates" | "group"> &
    Partial<ComparedTeam>,
): ComparedTeam {
  return {
    confederation: "CONMEBOL",
    groupLetter: "J",
    managerName: "Lionel Scaloni",
    fifaRankingPreTournament: 1,
    eloRating: 2104,
    stageCaption: "Group stage to semifinal",
    discipline: { yellowCards: 11, redCards: 0, fouls: 76, yellowPerMatch: 1.57 },
    squad: {
      rosterSize: 26,
      averageAge: 28.1,
      totalMarketValueEur: 812_000_000,
      youngestAge: 21,
      oldestAge: 36,
      under23Pct: 15.4,
      over30Pct: 23.1,
      topThreeValueSharePct: 34.2,
      distinctStarters: 14,
      starterMinutesSharePct: 78.4,
      transfermarktAverageAge: 27.8,
      transfermarktMarketValueEur: 790_000_000,
      transfermarktSquadSize: 26,
    },
    matchResults: [
      { stage: "MD1", opponentCode: "ALG", opponentName: "Algeria", score: "3–0", result: "W" },
      { stage: "SF", opponentCode: "BRA", opponentName: "Brazil", score: "1–2", result: "L" },
    ],
    topScorer: {
      playerId: argentinaFwd.id,
      name: argentinaFwd.name,
      position: "FWD",
      goals: 5,
      assists: 1,
      minutes: 490,
    },
    topAssister: {
      playerId: argentinaMid.id,
      name: argentinaMid.name,
      position: "MID",
      goals: 1,
      assists: 3,
      minutes: 580,
    },
    mostMinutes: {
      playerId: argentinaGk.id,
      name: argentinaGk.name,
      position: "GK",
      goals: 0,
      assists: 0,
      minutes: 630,
    },
    ...partial,
  };
}

export const sampleTeamComparison: TeamComparison = {
  id: "1-vs-2",
  scopeLabel: "WC 2026",
  teamA: side({
    id: "1",
    code: "ARG",
    name: "Argentina",
    standingLabel: "Semifinalist · out 1–2 to Brazil",
    record: { won: 5, drawn: 1, lost: 1, goalsFor: 14, goalsAgainst: 5 },
    goalDifference: 9,
    rates: RATES,
    group: { played: 3, points: 7, goalDifference: 5 },
  }),
  teamB: side({
    id: "2",
    code: "BRA",
    name: "Brazil",
    standingLabel: "Finalist · unbeaten so far",
    managerName: "Dorival Júnior",
    fifaRankingPreTournament: 5,
    eloRating: 1988,
    groupLetter: "C",
    stageCaption: "Group stage to final",
    record: { won: 6, drawn: 0, lost: 0, goalsFor: 13, goalsAgainst: 4 },
    goalDifference: 9,
    rates: { ...RATES, possessionPct: 52.1, goalsPerGame: 1.86, concededPerGame: 0.57, xgDifference: 4.1 },
    group: { played: 3, points: 9, goalDifference: 6 },
    discipline: { yellowCards: 8, redCards: 1, fouls: 90, yellowPerMatch: 1.14 },
    squad: {
      rosterSize: 26,
      averageAge: 27.4,
      totalMarketValueEur: 980_000_000,
      youngestAge: 19,
      oldestAge: 34,
      under23Pct: 19.2,
      over30Pct: 11.5,
      topThreeValueSharePct: 41.0,
      distinctStarters: 15,
      starterMinutesSharePct: 81.2,
      transfermarktAverageAge: null,
      transfermarktMarketValueEur: null,
      transfermarktSquadSize: null,
    },
    matchResults: [
      { stage: "MD1", opponentCode: "MAR", opponentName: "Morocco", score: "2–0", result: "W" },
      { stage: "SF", opponentCode: "ARG", opponentName: "Argentina", score: "2–1", result: "W" },
    ],
    topScorer: {
      playerId: brazilFwd.id,
      name: brazilFwd.name,
      position: "FWD",
      goals: 4,
      assists: 2,
      minutes: 520,
    },
    topAssister: {
      playerId: brazilFwd.id,
      name: brazilFwd.name,
      position: "FWD",
      goals: 4,
      assists: 2,
      minutes: 520,
    },
    mostMinutes: {
      playerId: brazilGk.id,
      name: brazilGk.name,
      position: "GK",
      goals: 0,
      assists: 0,
      minutes: 570,
    },
  }),
  comparedStats: [
    {
      label: "Possession",
      teamADisplay: "58.4%",
      teamBDisplay: "52.1%",
      fieldDisplay: "50.0%",
      teamAValue: 58.4,
      teamBValue: 52.1,
      fieldValue: 50,
      higherIsBetter: true,
      teamAIsBetter: true,
      teamBIsBetter: false,
    },
    {
      label: "Goals per game",
      teamADisplay: "2.00",
      teamBDisplay: "1.86",
      fieldDisplay: "1.20",
      teamAValue: 2,
      teamBValue: 1.86,
      fieldValue: 1.2,
      higherIsBetter: true,
      teamAIsBetter: true,
      teamBIsBetter: false,
    },
    {
      label: "Goals conceded / game",
      teamADisplay: "0.71",
      teamBDisplay: "0.57",
      fieldDisplay: "1.20",
      teamAValue: 0.71,
      teamBValue: 0.57,
      fieldValue: 1.2,
      higherIsBetter: false,
      teamAIsBetter: false,
      teamBIsBetter: true,
    },
    {
      label: "xG difference / game",
      teamADisplay: "+1.04",
      teamBDisplay: "+0.59",
      fieldDisplay: "+0.00",
      teamAValue: 1.04,
      teamBValue: 0.59,
      fieldValue: 0,
      higherIsBetter: true,
      teamAIsBetter: true,
      teamBIsBetter: false,
    },
  ],
  strengthsAndFlaws: [
    {
      side: "a",
      kind: "strength",
      label: "Possession",
      detail: "58.4% vs 52.1% · field 50.0%",
    },
    {
      side: "a",
      kind: "flaw",
      label: "Goals conceded / game",
      detail: "0.71 vs 0.57 · field 1.20",
    },
    {
      side: "b",
      kind: "strength",
      label: "Goals conceded / game",
      detail: "0.57 vs 0.71 · field 1.20",
    },
  ],
  meetings: [
    {
      matchId: "88",
      stage: "SF",
      teamAScore: 1,
      teamBScore: 2,
      teamAResult: "L",
      penaltyScore: null,
    },
  ],
  positions: [
    samplePositionGroup("GK", [argentinaGk], [brazilGk]),
    samplePositionGroup("DEF", [argentinaDef], [brazilDef]),
    samplePositionGroup("MID", [argentinaMid], [brazilMid]),
    samplePositionGroup("FWD", [argentinaFwd], [brazilFwd]),
  ],
};
