"""Live conversation socket. Every open client on a conversation reads the
same Redis stream, so a send from one device shows up on the others without
a refresh. The reply itself is still generated by `generate_chat_reply_task`.
"""

import asyncio
import json
import secrets
from uuid import UUID

from fastapi import APIRouter, WebSocket, WebSocketDisconnect, status
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.v1.auth.services.dependencies import JwtDataDep
from src.api.v1.chat.sse import client_message
from src.domain.chat.exceptions.chat_exceptions import ConversationOwnershipError
from src.domain.chat.services.chat_service import ChatService
from src.domain.chat.tools.registry import build_tool_registry
from src.infra.openrouter.client import get_openrouter_client
from src.infra.postgres.config import SessionFactory
from src.infra.postgres.repositories.chat_message_repository import get_chat_message_repository
from src.infra.postgres.repositories.conversation_repository import get_conversation_repository
from src.infra.postgres.repositories.match_analytics_repository import (
    get_match_analytics_repository,
)
from src.infra.postgres.repositories.player_analytics_repository import (
    get_player_analytics_repository,
)
from src.infra.postgres.repositories.team_analytics_repository import get_team_analytics_repository
from src.infra.redis.config import redis_client
from src.infra.redis.repositories.conversation_cache_repository import (
    get_conversation_cache_repository,
)
from src.infra.task_queue.chat_tasks import (
    TURN_IN_PROGRESS_TTL_SECONDS,
    is_stream_cursor,
    last_stream_cursor,
    serialize_user_message_event,
    turn_in_progress_key,
    turn_stream_key,
)
from src.infra.task_queue.pool import enqueue_chat_reply

router = APIRouter(tags=["chat"])

_TICKET_TTL_SECONDS = 30
_TURN_ALREADY_IN_PROGRESS = "A reply is already being generated for this conversation"
_READ_BLOCK_MS = 1_000


class TurnAlreadyInProgress(Exception):
    pass


def _ticket_key(ticket: str) -> str:
    return f"chat:ws-ticket:{ticket}"


def _chat_service(session: AsyncSession) -> ChatService:
    return ChatService(
        conversation_cache=get_conversation_cache_repository(redis_client),
        openrouter_client=get_openrouter_client(),
        tool_registry=build_tool_registry(
            get_team_analytics_repository(session),
            get_player_analytics_repository(session),
            get_match_analytics_repository(session),
        ),
        conversation_repo=get_conversation_repository(session),
        chat_message_repo=get_chat_message_repository(session),
        session=session,
    )


@router.post("/chat/ws-tickets", summary="Mint a one-time ticket for the live socket")
async def mint_ws_ticket(jwt_data: JwtDataDep) -> dict[str, str]:
    ticket = secrets.token_urlsafe(32)
    await redis_client.set(_ticket_key(ticket), jwt_data["sub"], ex=_TICKET_TTL_SECONDS)
    return {"ticket": ticket}


async def accept_chat_message(conversation_id: UUID, user_id: int, message: str) -> None:
    """Persists the user message, publishes it on the conversation stream,
    and enqueues reply generation. Every socket pumping that stream --
    including this one -- receives the same `user_message` entry.
    """
    async with SessionFactory() as session:
        chat_service = _chat_service(session)
        conversation = await chat_service.start_turn(
            conversation_id=conversation_id, user_id=user_id, first_message=message
        )
        cursor = await last_stream_cursor(str(conversation_id))
        reserved = await redis_client.set(
            turn_in_progress_key(str(conversation_id)),
            cursor,
            nx=True,
            ex=TURN_IN_PROGRESS_TTL_SECONDS,
        )
        if not reserved:
            raise TurnAlreadyInProgress()
        user_message = await chat_service.persist_user_message(conversation_id, message)
        await redis_client.xadd(
            turn_stream_key(str(conversation_id)),
            serialize_user_message_event(
                str(conversation.id), user_message.id, message, conversation.title
            ),
        )
        await enqueue_chat_reply(str(conversation_id), user_id, message, user_message.id)


async def _resume_cursor(conversation_id: str) -> str:
    """Where a newly attached socket starts reading.

    An in-progress turn replays from the cursor stored at reservation, which
    is before that turn's user message. An idle conversation starts at the
    end of the stream so history already loaded from Postgres is not replayed.
    """
    stored = await redis_client.get(turn_in_progress_key(conversation_id))
    if isinstance(stored, str) and is_stream_cursor(stored):
        return stored
    return await last_stream_cursor(conversation_id)


async def _pump(websocket: WebSocket, conversation_id: str, send_lock: asyncio.Lock) -> None:
    cursor = await _resume_cursor(conversation_id)
    stream_key = turn_stream_key(conversation_id)
    while True:
        response = await redis_client.xread({stream_key: cursor}, block=_READ_BLOCK_MS)
        if not response:
            continue
        _name, entries = response[0]
        for entry_id, fields in entries:
            cursor = entry_id
            payload = client_message(entry_id, fields["event_type"], json.loads(fields["payload"]))
            async with send_lock:
                await websocket.send_json(payload)


async def _receive(
    websocket: WebSocket, conversation_id: UUID, user_id: int, send_lock: asyncio.Lock
) -> None:
    while True:
        raw = await websocket.receive_text()
        try:
            body = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if not isinstance(body, dict) or body.get("type") != "send":
            continue
        message = body.get("message")
        if not isinstance(message, str) or not message.strip():
            continue
        try:
            await accept_chat_message(conversation_id, user_id, message.strip())
        except TurnAlreadyInProgress:
            async with send_lock:
                await websocket.send_json({"type": "rejected", "detail": _TURN_ALREADY_IN_PROGRESS})
        except ConversationOwnershipError:
            async with send_lock:
                await websocket.send_json({"type": "rejected", "detail": "Conversation not found"})


@router.websocket("/conversations/{conversation_id}/live")
async def conversation_live(websocket: WebSocket, conversation_id: UUID) -> None:
    ticket = websocket.query_params.get("ticket")
    user_id_raw = await redis_client.getdel(_ticket_key(ticket)) if ticket else None
    if user_id_raw is None:
        await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
        return
    user_id = int(user_id_raw)

    async with SessionFactory() as session:
        available = await get_conversation_repository(session).is_available_to(
            conversation_id, user_id
        )
    if not available:
        await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
        return

    await websocket.accept()
    send_lock = asyncio.Lock()
    pump_task = asyncio.create_task(_pump(websocket, str(conversation_id), send_lock))
    receive_task = asyncio.create_task(_receive(websocket, conversation_id, user_id, send_lock))
    try:
        done, pending = await asyncio.wait(
            {pump_task, receive_task}, return_when=asyncio.FIRST_COMPLETED
        )
        for task in pending:
            task.cancel()
        for task in done:
            exception = task.exception()
            if exception is not None and not isinstance(exception, WebSocketDisconnect):
                raise exception
    finally:
        pump_task.cancel()
        receive_task.cancel()
        await asyncio.gather(pump_task, receive_task, return_exceptions=True)
