"""add transfermarkt enrichment tables

Revision ID: db800dd3ee39
Revises: 7b5d653193ee
Create Date: 2026-09-18 13:27:44.567291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db800dd3ee39'
down_revision: Union[str, Sequence[str], None] = '7b5d653193ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_club',
    sa.Column('club_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('club_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domestic_competition_id', sa.String(), nullable=True),
    sa.Column('total_market_value_eur', sa.Integer(), nullable=True),
    sa.Column('squad_size', sa.Integer(), nullable=True),
    sa.Column('average_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('stadium_seats', sa.Integer(), nullable=True),
    sa.Column('stadium_name', sa.String(), nullable=True),
    sa.Column('coach_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('club_id', name=op.f('real_club_pkey'))
    )
    op.create_table('real_national_team',
    sa.Column('national_team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('confederation', sa.String(), nullable=False),
    sa.Column('fifa_ranking', sa.Integer(), nullable=True),
    sa.Column('squad_size', sa.Integer(), nullable=True),
    sa.Column('average_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('total_market_value_eur', sa.Integer(), nullable=True),
    sa.Column('coach_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('national_team_id', name=op.f('real_national_team_pkey'))
    )
    op.create_table('real_player',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_of_birth', sa.String(), nullable=True),
    sa.Column('country_of_citizenship', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('sub_position', sa.String(), nullable=True),
    sa.Column('foot', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('current_club_id', sa.Integer(), nullable=True),
    sa.Column('current_national_team_id', sa.Integer(), nullable=True),
    sa.Column('international_caps', sa.Integer(), nullable=True),
    sa.Column('international_goals', sa.Integer(), nullable=True),
    sa.Column('market_value_eur', sa.Integer(), nullable=True),
    sa.Column('highest_market_value_eur', sa.Integer(), nullable=True),
    sa.Column('contract_expiration_date', sa.Date(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_club_id'], ['real_club.club_id'], name=op.f('real_player_current_club_id_fkey')),
    sa.ForeignKeyConstraint(['current_national_team_id'], ['real_national_team.national_team_id'], name=op.f('real_player_current_national_team_id_fkey')),
    sa.PrimaryKeyConstraint('player_id', name=op.f('real_player_pkey'))
    )
    op.create_table('real_player_season_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['real_player_id'], ['real_player.player_id'], name=op.f('real_player_season_stat_real_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('real_player_season_stat_pkey')),
    sa.UniqueConstraint('real_player_id', 'season', 'competition_id', name=op.f('real_player_season_stat_real_player_id_key'))
    )
    op.create_table('real_player_valuation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_player_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('market_value_eur', sa.Integer(), nullable=False),
    sa.Column('club_name_at_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['real_player_id'], ['real_player.player_id'], name=op.f('real_player_valuation_real_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('real_player_valuation_pkey'))
    )
    op.create_table('real_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_player_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('transfer_season', sa.String(), nullable=True),
    sa.Column('from_club_id', sa.Integer(), nullable=True),
    sa.Column('to_club_id', sa.Integer(), nullable=True),
    sa.Column('from_club_name', sa.String(), nullable=False),
    sa.Column('to_club_name', sa.String(), nullable=False),
    sa.Column('transfer_fee_eur', sa.Numeric(), nullable=True),
    sa.Column('market_value_at_transfer_eur', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['from_club_id'], ['real_club.club_id'], name=op.f('real_transfer_from_club_id_fkey')),
    sa.ForeignKeyConstraint(['real_player_id'], ['real_player.player_id'], name=op.f('real_transfer_real_player_id_fkey')),
    sa.ForeignKeyConstraint(['to_club_id'], ['real_club.club_id'], name=op.f('real_transfer_to_club_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('real_transfer_pkey'))
    )
    op.create_table('player_identity_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('real_player_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.Enum('EXACT_NAME_DOB', 'EXACT_NAME_TEAM', 'FUZZY_NAME', 'MANUAL', name='player_match_method'), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name=op.f('player_identity_link_player_id_fkey')),
    sa.ForeignKeyConstraint(['real_player_id'], ['real_player.player_id'], name=op.f('player_identity_link_real_player_id_fkey')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], name=op.f('player_identity_link_reviewed_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('player_identity_link_pkey')),
    sa.UniqueConstraint('player_id', name=op.f('player_identity_link_player_id_key')),
    sa.UniqueConstraint('real_player_id', name=op.f('player_identity_link_real_player_id_key'))
    )
    op.add_column('team', sa.Column('real_national_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('team_real_national_team_id_fkey'), 'team', 'real_national_team', ['real_national_team_id'], ['national_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('team_real_national_team_id_fkey'), 'team', type_='foreignkey')
    op.drop_column('team', 'real_national_team_id')
    op.drop_table('player_identity_link')
    op.drop_table('real_transfer')
    op.drop_table('real_player_valuation')
    op.drop_table('real_player_season_stat')
    op.drop_table('real_player')
    op.drop_table('real_national_team')
    op.drop_table('real_club')
    # ### end Alembic commands ###
