"""create initial schema

Revision ID: 7b5d653193ee
Revises: 
Create Date: 2026-09-17 23:10:34.769810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5d653193ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee',
    sa.Column('referee_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('avg_cards_per_game', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('referee_id', name=op.f('referee_pkey'))
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('fifa_code', sa.String(), nullable=False),
    sa.Column('group_letter', sa.String(), nullable=False),
    sa.Column('confederation', sa.String(), nullable=False),
    sa.Column('fifa_ranking_pre_tournament', sa.Integer(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team_id', name=op.f('team_pkey'))
    )
    op.create_table('tournament_stage',
    sa.Column('stage_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('is_knockout', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('stage_id', name=op.f('tournament_stage_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=True)
    op.create_table('venue',
    sa.Column('venue_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('stadium_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_meters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('venue_id', name=op.f('venue_pkey'))
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('club_team', sa.String(), nullable=False),
    sa.Column('market_value_eur', sa.Integer(), nullable=False),
    sa.Column('caps', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('player_team_id_fkey')),
    sa.PrimaryKeyConstraint('player_id', name=op.f('player_pkey'))
    )
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kickoff_time_utc', sa.Time(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_penalty_score', sa.Integer(), nullable=True),
    sa.Column('away_penalty_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=False),
    sa.Column('away_xg', sa.Float(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('player_of_the_match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.team_id'], name=op.f('match_away_team_id_fkey')),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.team_id'], name=op.f('match_home_team_id_fkey')),
    sa.ForeignKeyConstraint(['player_of_the_match_id'], ['player.player_id'], name=op.f('match_player_of_the_match_id_fkey')),
    sa.ForeignKeyConstraint(['referee_id'], ['referee.referee_id'], name=op.f('match_referee_id_fkey')),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stage.stage_id'], name=op.f('match_stage_id_fkey')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], name=op.f('match_venue_id_fkey')),
    sa.PrimaryKeyConstraint('match_id', name=op.f('match_pkey'))
    )
    op.create_table('player_stat',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('matches_started', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('penalty_goals', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name=op.f('player_stat_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('player_stat_team_id_fkey')),
    sa.PrimaryKeyConstraint('player_id', name=op.f('player_stat_pkey'))
    )
    op.create_table('match_event',
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], name=op.f('match_event_match_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name=op.f('match_event_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('match_event_team_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('match_event_pkey'))
    )
    op.create_table('match_lineup',
    sa.Column('lineup_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_starting_xi', sa.Boolean(), nullable=False),
    sa.Column('tactical_position', sa.String(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], name=op.f('match_lineup_match_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name=op.f('match_lineup_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('match_lineup_team_id_fkey')),
    sa.PrimaryKeyConstraint('lineup_id', name=op.f('match_lineup_pkey'))
    )
    op.create_table('match_team_stat',
    sa.Column('match_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('possession_pct', sa.Integer(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('corners', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('offsides', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('player_of_the_match', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], name=op.f('match_team_stat_match_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('match_team_stat_team_id_fkey')),
    sa.PrimaryKeyConstraint('match_id', 'team_id', name=op.f('match_team_stat_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_team_stat')
    op.drop_table('match_lineup')
    op.drop_table('match_event')
    op.drop_table('player_stat')
    op.drop_table('match')
    op.drop_table('player')
    op.drop_table('venue')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_table('user')
    op.drop_table('tournament_stage')
    op.drop_table('team')
    op.drop_table('referee')
    # ### end Alembic commands ###
