"""add real match tables and ingestion job

Revision ID: 14ba028c3574
Revises: db800dd3ee39
Create Date: 2026-09-19 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ba028c3574'
down_revision: Union[str, Sequence[str], None] = 'db800dd3ee39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('SYNTHETIC_UPLOAD', 'TRANSFERMARKT_SYNC', name='ingestion_job_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='ingestion_job_status'), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], name=op.f('ingestion_job_requested_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_job_pkey'))
    )
    op.create_index(op.f('ingestion_job_status_idx'), 'ingestion_job', ['status'], unique=False)
    op.create_table('real_club_game',
    sa.Column('real_game_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('real_club_id', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('own_position', sa.String(), nullable=True),
    sa.Column('own_manager_name', sa.String(), nullable=True),
    sa.Column('opponent_club_id', sa.Integer(), nullable=True),
    sa.Column('opponent_goals', sa.Integer(), nullable=True),
    sa.Column('opponent_position', sa.String(), nullable=True),
    sa.Column('opponent_manager_name', sa.String(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_club_id'], ['real_club.club_id'], name=op.f('real_club_game_opponent_club_id_fkey')),
    sa.ForeignKeyConstraint(['real_club_id'], ['real_club.club_id'], name=op.f('real_club_game_real_club_id_fkey')),
    sa.PrimaryKeyConstraint('real_game_id', 'real_club_id', name=op.f('real_club_game_pkey'))
    )
    op.create_index(op.f('real_club_game_opponent_club_id_idx'), 'real_club_game', ['opponent_club_id'], unique=False)
    op.create_table('real_game_lineup',
    sa.Column('game_lineups_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('real_game_id', sa.Integer(), nullable=False),
    sa.Column('real_player_id', sa.Integer(), nullable=False),
    sa.Column('real_club_id', sa.Integer(), nullable=False),
    sa.Column('lineup_type', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('squad_number', sa.Integer(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('lineup_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['real_club_id'], ['real_club.club_id'], name=op.f('real_game_lineup_real_club_id_fkey')),
    sa.ForeignKeyConstraint(['real_player_id'], ['real_player.player_id'], name=op.f('real_game_lineup_real_player_id_fkey')),
    sa.PrimaryKeyConstraint('game_lineups_id', name=op.f('real_game_lineup_pkey'))
    )
    op.create_index(op.f('real_game_lineup_real_club_id_idx'), 'real_game_lineup', ['real_club_id'], unique=False)
    op.create_index(op.f('real_game_lineup_real_game_id_idx'), 'real_game_lineup', ['real_game_id'], unique=False)
    op.create_index(op.f('real_game_lineup_real_player_id_idx'), 'real_game_lineup', ['real_player_id'], unique=False)
    op.create_table('real_match_event',
    sa.Column('game_event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('real_game_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('real_club_id', sa.Integer(), nullable=True),
    sa.Column('club_name_at_time', sa.String(), nullable=True),
    sa.Column('real_player_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('player_in_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assist_player_id'], ['real_player.player_id'], name=op.f('real_match_event_assist_player_id_fkey')),
    sa.ForeignKeyConstraint(['player_in_id'], ['real_player.player_id'], name=op.f('real_match_event_player_in_id_fkey')),
    sa.ForeignKeyConstraint(['real_club_id'], ['real_club.club_id'], name=op.f('real_match_event_real_club_id_fkey')),
    sa.ForeignKeyConstraint(['real_player_id'], ['real_player.player_id'], name=op.f('real_match_event_real_player_id_fkey')),
    sa.PrimaryKeyConstraint('game_event_id', name=op.f('real_match_event_pkey'))
    )
    op.create_index(op.f('real_match_event_real_club_id_idx'), 'real_match_event', ['real_club_id'], unique=False)
    op.create_index(op.f('real_match_event_real_game_id_idx'), 'real_match_event', ['real_game_id'], unique=False)
    op.create_index(op.f('real_match_event_real_player_id_idx'), 'real_match_event', ['real_player_id'], unique=False)
    # `add_column` below (an ALTER TABLE, not a CREATE TABLE) does not emit
    # the enum type's own CREATE TYPE -- unlike a brand-new table's inline
    # enum column, it must be created explicitly first.
    link_review_status = postgresql.ENUM(
        "PENDING", "APPROVED", "REJECTED", name="link_review_status"
    )
    link_review_status.create(op.get_bind())
    op.add_column('player_identity_link', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='link_review_status'), server_default='PENDING', nullable=False))
    op.create_index(op.f('player_identity_link_status_idx'), 'player_identity_link', ['status'], unique=False)
    # ### end Alembic commands ###

    # Data migration: backfill `status` from the existing `reviewed_by_admin`
    # boolean so already-reviewed rows are not silently reset to `pending`.
    # The column-level server_default already covers rows created during
    # this same transaction; this UPDATE covers pre-existing rows.
    op.execute(
        "UPDATE player_identity_link SET status = 'APPROVED' WHERE reviewed_by_admin = true"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('player_identity_link_status_idx'), table_name='player_identity_link')
    op.drop_column('player_identity_link', 'status')
    postgresql.ENUM(name="link_review_status").drop(op.get_bind())
    op.drop_index(op.f('real_match_event_real_player_id_idx'), table_name='real_match_event')
    op.drop_index(op.f('real_match_event_real_game_id_idx'), table_name='real_match_event')
    op.drop_index(op.f('real_match_event_real_club_id_idx'), table_name='real_match_event')
    op.drop_table('real_match_event')
    op.drop_index(op.f('real_game_lineup_real_player_id_idx'), table_name='real_game_lineup')
    op.drop_index(op.f('real_game_lineup_real_game_id_idx'), table_name='real_game_lineup')
    op.drop_index(op.f('real_game_lineup_real_club_id_idx'), table_name='real_game_lineup')
    op.drop_table('real_game_lineup')
    op.drop_index(op.f('real_club_game_opponent_club_id_idx'), table_name='real_club_game')
    op.drop_table('real_club_game')
    op.drop_index(op.f('ingestion_job_status_idx'), table_name='ingestion_job')
    op.drop_table('ingestion_job')
    # ### end Alembic commands ###

    # `drop_table` does not drop the enum types it used inline; drop them
    # explicitly so a downgrade -> upgrade roundtrip is fully reversible.
    postgresql.ENUM(name="ingestion_job_status").drop(op.get_bind())
    postgresql.ENUM(name="ingestion_job_type").drop(op.get_bind())
