"""national_team: auto-create unmatched Transfermarkt countries, rename real_national_team_id

Revision ID: c47e91b3a5d8
Revises: a1c47f92d6e3
Create Date: 2026-09-20 00:00:03.000001

`real_national_team_id` renamed to `transfermarkt_id` -- "real" was a
leftover from when Transfermarkt data lived in a separate `real_*` table
(see the prior migration); on the merged `national_team` table it reads as
"the true id" instead of "the id from Transfermarkt", which is what it
actually is.

The Transfermarkt sync's national_teams step can now CREATE a row for a
country with no WC2026 match, instead of only ever UPDATing one. `team_id`
becomes a Postgres IDENTITY column (`GENERATED BY DEFAULT AS IDENTITY`,
seeded to continue after the current max) so that insert path can omit it
and let the database assign the next id atomically -- computing
"MAX(team_id) + 1" in application code would race under concurrent syncs
(arq allows more than one running job at a time). `fifa_code`,
`group_letter`, `fifa_ranking_pre_tournament`, `elo_rating`, and
`manager_name` become nullable: they're WC2026-tournament-specific
concepts a country that never qualified simply doesn't have.

`downgrade()` deletes any row with no `fifa_code` before restoring the
NOT NULL constraints -- those are exactly the rows this migration's
auto-create path can produce, and they have no valid value for a
WC2026-only column to hold.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c47e91b3a5d8'
down_revision: Union[str, Sequence[str], None] = 'a1c47f92d6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE national_team RENAME COLUMN real_national_team_id TO transfermarkt_id")
    op.execute(
        "ALTER TABLE national_team RENAME CONSTRAINT "
        "national_team_real_national_team_id_key TO national_team_transfermarkt_id_key"
    )

    op.alter_column('national_team', 'fifa_code', nullable=True)
    op.alter_column('national_team', 'group_letter', nullable=True)
    op.alter_column('national_team', 'fifa_ranking_pre_tournament', nullable=True)
    op.alter_column('national_team', 'elo_rating', nullable=True)
    op.alter_column('national_team', 'manager_name', nullable=True)

    op.execute("ALTER TABLE national_team ALTER COLUMN team_id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('national_team', 'team_id'), "
        "COALESCE((SELECT MAX(team_id) FROM national_team), 0) + 1, false)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE national_team ALTER COLUMN team_id DROP IDENTITY IF EXISTS")

    # Only a row this migration's auto-create path produced has no
    # fifa_code -- it has no valid WC2026-only values to restore either.
    op.execute("DELETE FROM national_team WHERE fifa_code IS NULL")
    op.alter_column('national_team', 'manager_name', nullable=False)
    op.alter_column('national_team', 'elo_rating', nullable=False)
    op.alter_column('national_team', 'fifa_ranking_pre_tournament', nullable=False)
    op.alter_column('national_team', 'group_letter', nullable=False)
    op.alter_column('national_team', 'fifa_code', nullable=False)

    op.execute(
        "ALTER TABLE national_team RENAME CONSTRAINT "
        "national_team_transfermarkt_id_key TO national_team_real_national_team_id_key"
    )
    op.execute("ALTER TABLE national_team RENAME COLUMN transfermarkt_id TO real_national_team_id")
